<a href="https://colab.research.google.com/github/maria2021831011/machine_learning/blob/main/4_6_train_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [3]:
data=pd.read_csv('/content/data.csv')
data.head()

         id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
#getting the statistical measures of data
data.describe()

                 id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

In [5]:
data.groupby('diagnosis').mean()

                     id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
diagnosis                             ...
B          2.654382e+07    12.146524  ...                 0.079442          NaN
M          3.681805e+07    17.462830  ...                 0.091530          NaN

[2 rows x 32 columns]

In [6]:
#separating the data and lebels
x=data.drop(columns='diagnosis',axis=1)
y=data['diagnosis']

In [7]:
print(x)

           id  radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0      842302        17.99         10.38  ...          0.4601                  0.11890          NaN
1      842517        20.57         17.77  ...          0.2750                  0.08902          NaN
2    84300903        19.69         21.25  ...          0.3613                  0.08758          NaN
3    84348301        11.42         20.38  ...          0.6638                  0.17300          NaN
4    84358402        20.29         14.34  ...          0.2364                  0.07678          NaN
..        ...          ...           ...  ...             ...                      ...          ...
564    926424        21.56         22.39  ...          0.2060                  0.07115          NaN
565    926682        20.13         28.25  ...          0.2572                  0.06637          NaN
566    926954        16.60         28.08  ...          0.2218                  0.07820          NaN
567    927241        20.60         29.33  ...          0.4087                  0.12400          NaN
568     92751         7.76         24.54  ...          0.2871                  0.07039          NaN

[569 rows x 32 columns]

In [8]:
print(y)

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [9]:
#standardized data
scaler=StandardScaler()
scaler.fit(x)
standardized_data=scaler.transform(x)
print(standardized_data)

[[-0.23640517  1.09706398 -2.07333501 ...  2.75062224  1.93701461
          nan]
 [-0.23640344  1.82982061 -0.35363241 ... -0.24388967  0.28118999
          nan]
 [ 0.43174109  1.57988811  0.45618695 ...  1.152255    0.20139121
          nan]
 ...
 [-0.23572747  0.70228425  2.0455738  ... -1.10454895 -0.31840916
          nan]
 [-0.23572517  1.83834103  2.33645719 ...  1.91908301  2.21963528
          nan]
 [-0.24240586 -1.80840125  1.22179204 ... -0.04813821 -0.75120669
          nan]]

/usr/local/lib/python3.10/dist-packages/sklearn/utils/extmath.py:1137: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.10/dist-packages/sklearn/utils/extmath.py:1142: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.10/dist-packages/sklearn/utils/extmath.py:1162: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [10]:
x=standardized_data
y=data['diagnosis']
print(x)
print(y)

[[-0.23640517  1.09706398 -2.07333501 ...  2.75062224  1.93701461
          nan]
 [-0.23640344  1.82982061 -0.35363241 ... -0.24388967  0.28118999
          nan]
 [ 0.43174109  1.57988811  0.45618695 ...  1.152255    0.20139121
          nan]
 ...
 [-0.23572747  0.70228425  2.0455738  ... -1.10454895 -0.31840916
          nan]
 [-0.23572517  1.83834103  2.33645719 ...  1.91908301  2.21963528
          nan]
 [-0.24240586 -1.80840125  1.22179204 ... -0.04813821 -0.75120669
          nan]]
0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [12]:
#spliting train data test data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)
print(x.shape,x_train.shape,x_test.shape)

(569, 32) (455, 32) (114, 32)